add --pretokenized flag
tomlimi/entangled_in_scripts pull request #6
Opened 2024-06-20 14:13 UTC by KathyHaem

to allow the script to read already-tokenized data.
I've moved the loading of the tokenizer to the main() function because it seemed cleaner than loading it somewhere hidden -> the various file path things are handled outside of the metrics calculation.

Please do test that it still runs.

### Extra context:
I've disentangled this from the `tokenizer_type` flag and MODELS_BY_TYPE situation that you may have also seen. While that was convenient for me, it wasn't actually clean and logically connected to the "pretokenized" flag.

So as it is right now, the script would still assume that the tokenizer either is or should be saved in the output directory. This didn't work for me when I was using tokenizers saved elsewhere on the system but wanted to write the script output to my own files.

I MAY end up making the ability to use a tokenizer saved somewhere else, with a short name, another PR down the line, but right now it's admittedly not a priority to clean up that code.

2024-08-01 18:13 UTC, tomlimi commented on src/compute_token_frequency.py
GitHub diff shows the changes in this file wieredly.
It seems that the whole code was changed, maybe due to different whitespace?
Could you revert changes and reapply just in the changed lines for easier comparison?

2024-08-01 18:18 UTC, tomlimi commented
Thanks for these changing, your concept should make the code clearer. I have a problem comparing comparing the updated version of `src/compute_token_frequency.py`, it seems that the whole code was changed while the updates are actually local. Could you try to revert theses changes and re-apply only in the lines that are different.

2024-08-05 09:53 UTC, KathyHaem commented on src/compute_token_frequency.py
Hey, so I tried to recommit but that didn't work so far. It turns out that compute_token_frequency is for some reason the one file indexed with CRLF (Windows) line endings, whereas the standard for checking in files seems to be LF (Unix). That's certainly what my git installation did, and I'm currently trying to see if I can force it to revert to CRLF for that one file in order to get a proper diff. Though in general it's probably good to switch to LF line endings in the index ;)

2024-08-05 11:48 UTC, KathyHaem commented on src/compute_token_frequency.py
(discussed separately, leaving the line endings as LF and sent a diff from the IDE which manages to only show actual changes)

2024-08-07 14:45 UTC, tomlimi requested changes
I went over code, it looks great! I have just two requests:

1. Please add handling of error when token is not found in the tokenizer's vocabulary. It would indicate that provided tokenizer does not match the tokenizer used in pretokenization step (see comment).
2. Please add as short description of `--pretokenized` flag to README. Please write how tokens should be separated in the data files (by spaces?) and that the tokenizer used for pretokenization should match the one provided by `--tokenizer_name`.

I think, in future when `--pretokenized` flag would be used we could drop the requirement of providing `--tokenizer_name`. The vocabulary could be then inferred based on pretokenized files. But it's out of scope of this PR.

2024-08-07 14:45 UTC, tomlimi commented on src/compute_token_frequency.py
> +                            idx = vocab[tok]
Please add error handling in case when token is not found in vocab, i.e. mismatch between tokenizer and tokenized text.

2024-08-08 15:48 UTC, tomlimi approved these changes

2024-08-08 15:48 UTC, tomlimi commented on src/compute_token_frequency.py
> +                                print(f"Token '{tok}' not in vocabulary. Please ensure the tokenizer matches the "
looks great! 🙌

2024-08-08 15:48 UTC, tomlimi commented on README.md
> +  `tokenizer_name` must match the tokenizer that was used.
Awsome, it's clear now!

2024-08-08 15:56 UTC, tomlimi commented
Looks excellent after small changes, I tested `--pretokenized` flag behavior with flores-dev data tokenized with gemma.
With following scenarios:
1. Computing tokenizer properties on raw (not tokenized) files:
```
python src/evaluate_tokenizer.py -o tokenizers -d data/flores-dev/ar.pretok.tok data/flores-dev/tr.pretok.tok data/flores-dev/zh.pretok.tok data/flores-dev/el.pretok.tok data/flores-dev/es.pretok.tok data/flores-dev/en.pretok.tok -l ar tr zh el es en -t google/gemma-2b
```

2. Computing tokenizer properties on tokenized files with `--pretokenized` flag. It should return the same result if special tokens are present in tokenized files.
```
python src/evaluate_tokenizer.py -o tokenizers -d data/flores-dev/ar.gemma.tok data/flores-dev/tr.gemma.tok data/flores-dev/zh.gemma.tok data/flores-dev/el.gemma.tok data/flores-dev/es.gemma.tok data/flores-dev/en.gemma.tok -l ar tr zh el es en --pretokenized -t google/gemma-2b 
```

3. Trying computing properties on tokenized files with mismatch between the 
/
/tokenizer used for tokenization and provided by `--tokenizer` flag. It should fail 

```
python src/evaluate_tokenizer.py -o tokenizers -d data/flores-dev/ar.gemma.tok data/flores-dev/tr.gemma.tok data/flores-dev/zh.gemma.tok data/flores-dev/el.gemma.tok data/flores-dev/es.gemma.tok data/flores-dev/en.gemma.tok -l ar tr zh el es en --pretokenized -t facebook/xlm-v-base 
```

2024-08-08 15:57 UTC, merged